apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.apiTokenSecretName | default "cloudflare-api-token" }}
  namespace: {{ .Release.Namespace | default "default" }}
type: Opaque
stringData:
  apiToken: {{ required "cloudflare.apiToken is required" .Values.cloudflare.apiToken | quote }}
