{{- if .Values.installCustomResources }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.apiTokenSecretName | default "cloudflare-api-token" }}
  namespace: {{ .Release.namespace | default "default" }}
type: Opaque
stringData:
  api-token: {{ required "cloudflare.apiToken is required" .Values.cloudflare.apiToken | quote }}
{{- end }}
