apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.apiTokenSecretName }}
  namespace: cert-manager
type: Opaque
stringData:
  api-token: {{ required "cloudflare.apiToken is required" .Values.cloudflare.apiToken | quote }}
