installCustomResources: true

cloudflare:
  # Do not set a default value here; the token will be provided via --set.
  apiToken: ""
  apiTokenSecretName: "cloudflare-api-token"

external-dns:
  provider:
    name: cloudflare
  sources:
    - service
    - ingress
  domainFilters:
    - brians.computer
    - local.brians.computer
  logLevel: debug
  extraArgs:
    - "--cloudflare-dns-records-per-page=5000"
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: apiToken
