network:
  version: 2
  renderer: networkd
  ethernets:
    end0:
      addresses:
        - 192.168.4.184/22
      routes:
        - to: default
          via: 192.168.4.1
      nameservers:
        addresses:
          - 192.168.4.1
      dhcp4: true
      optional: true
