apiVersion: v2
name: cert-manager-wrapper
description: A wrapper chart for cert-manager with custom resources.
version: 0.1.0
appVersion: "v1.17.1"

dependencies:
  - name: cert-manager
    version: "v1.17.1"
    repository: "https://charts.jetstack.io"
