apiVersion: v2
name: traefik-install
description: K3s-equivalent Traefik install with dashboard and logs
type: application
version: 0.1.0
dependencies:
  - name: traefik
    version: 24.0.0
    repository: https://traefik.github.io/charts
