traefik:
  daemonset:
    enabled: true
  deployment:
    enabled: false
  api:
    insecure: true
  dashboard:
    enabled: true
  logs:
    access:
      enabled: true
  additionalArguments:
    - "--providers.kubernetescrd"
    - "--providers.kubernetesingress"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
  service:
    type: LoadBalancer
    ports:
      web:
        port: 80
      websecure:
        port: 443
      traefik:
        port: 9000
