deployment:
  enabled: true
  kind: DaemonSet

api:
  insecure: true
  dashboard: true

logs:
  access:
    enabled: true

ports:
  ssh:
    port: 2222
    exposedPort: 22
    expose:
      default: true
    protocol: TCP
