apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
    api:
      insecure: true
    ports:
      traefik:
        expose:
          default: true
    logs:
      access:
        enabled: true
