apiVersion: v2
name: kube-prometheus-stack-install
description: Wrapper chart for kube-prometheus-stack (Prometheus, Grafana, Alertmanager)
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "84.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: prometheus-blackbox-exporter
    version: "11.10.0"
    repository: "https://prometheus-community.github.io/helm-charts"
