apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: postgres
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.brians.computer
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: postgres
    role: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
