apiVersion: v2
name: loki-install
description: Wrapper chart for Grafana Loki (monolithic mode)
version: 0.1.0
dependencies:
  - name: loki
    version: "13.6.2"
    repository: "https://grafana-community.github.io/helm-charts"
