apiVersion: v2
name: loki-install
description: Wrapper chart for Grafana Loki (single-binary mode)
version: 0.1.0
dependencies:
  - name: loki
    version: "6.6.4"
    repository: "https://grafana.github.io/helm-charts"
