apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2Advertisement.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    {{- toYaml .Values.l2Advertisement.ipAddressPools | nindent 4 }}
